#!/bin/sh
set -e

# Fetch the database credentials
DB_CREDS_FILE="/var/www/.db-creds"

aws secretsmanager get-secret-value \
	--secret-id $DB_CREDS_SECRET_ID \
	--query SecretString \
	--output text \
	> $DB_CREDS_FILE

DB_USERNAME=$(jq -r .username $DB_CREDS_FILE)
DB_PASSWORD=$(jq -r .password $DB_CREDS_FILE)
DB_HOST=$(jq -r .host $DB_CREDS_FILE)

# Generate a hash salt file if needed
[ ! -f /mnt/efs/hash_salt ] && (php -r "print substr(base64_encode(random_bytes(1024)), 0, 64);" > /mnt/efs/hash_salt)

# Append configuration to the settings.php file
echo "\$databases['default']['default']['driver'] = 'mysql';" >> /var/www/html/sites/default/settings.php
echo "\$databases['default']['default']['database'] = '$DB_USERNAME';" >> /var/www/html/sites/default/settings.php
echo "\$databases['default']['default']['username'] = '$DB_USERNAME';" >> /var/www/html/sites/default/settings.php
echo "\$databases['default']['default']['password'] = '$DB_PASSWORD';" >> /var/www/html/sites/default/settings.php
echo "\$databases['default']['default']['host'] = '$DB_HOST';" >> /var/www/html/sites/default/settings.php
echo "\$settings['hash_salt'] = file_get_contents('/mnt/efs/hash_salt');" >> /var/www/html/sites/default/settings.php
echo "\$settings['config_sync_directory'] = 'sites/default/files/sync';" >> /var/www/html/sites/default/settings.php

# Replace the Drupal files directory with a link to the EFS filesystem
mkdir -p /mnt/efs/files
rm -rf /var/www/html/sites/default/files
ln -s /mnt/efs/files /var/www/html/sites/default/files
chmod -R 777 /var/www/html/sites/default/files

# Start Apache unless another command is given
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi
exec "$@"
